### ISSUE TITLE
Looking to partner?

### ISSUE THREAD

**Issue by SwimmingTuna** [drachentrix/Lord-of-the-Mysteries#1]
I'm also working on a lord of the mysteries mod and am decently well into it, but solo deving it is pretty hard lmao. Would you be down tocollab on this since as you know it's a lot of work. Here's my project: https://github.com/SwimmingTuna/Lord-of-the-Mysteries

if so, my discord is adaaaaaaaaaam or tuna#5585

**Comment by drachentrix** [comment]
hey,
sounds interesting but I currently don't have that much time under the week. On weekends I have a bit more . So I could do some things but my focus lies on other things. Is this still good for u?

**Comment by SwimmingTuna** [comment]
Yeah no worries at all, I'm busy with athletics and school too, any help is good help, contact me on disc to talk more ^^
